### ISSUE TITLE
[启动报错]Error: net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set

### ISSUE THREAD

**Issue by Aeko233** [MCTeamPotato/MultiOfflineFix#1]
环境：Minecraft1.16.5，Fabric0.14.21

[22:05:18] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.21
[22:05:18] [main/WARN]: Mod resolution failed
[22:05:18] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE multiofflinefix 1.0.1+1.16.5 {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE multiofflinefix 1.0.1+1.16.5]
[22:05:18] [main/INFO]: Reason: [HARD_DEP multiofflinefix 1.0.1+1.16.5 {depends fabric @ [*]}]
[22:05:18] [main/INFO]: Fix: add [add:fabric 1 ([(-∞,∞)])], remove [], replace []
[22:05:18] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'MultiOfflineFix' (multiofflinefix) 1.0.1+1.16.5 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) [JavaWrapper.jar:?]

**Comment by Aeko233** [comment]
It was my fault.: (
